#!/bin/bash
# Helper script to remind user to use external terminal for viewer

echo "============================================================"
echo "VS Code Remote SSH - X11 Viewer Setup"
echo "============================================================"
echo ""
echo "VS Code Remote SSH terminals may not have X11 forwarding enabled."
echo ""
echo "RECOMMENDED: Use a separate terminal for the viewer"
echo ""
echo "Steps:"
echo "1. Open a NEW terminal on your Windows machine"
echo "   (Windows Terminal, PowerShell, or CMD)"
echo ""
echo "2. Connect with X11 forwarding:"
echo "   ssh -Y hraspi"
echo ""
echo "3. In that terminal, run:"
echo "   source /home/hpalin/py311/bin/activate"
echo "   cd /home/hpalin/CS437Lab1/software"
echo "   python3 object_detection.py --viewer"
echo ""
echo "============================================================"
echo "Alternative: Try setting DISPLAY in VS Code terminal"
echo "============================================================"
echo ""
echo "In VS Code terminal, try:"
echo "  export DISPLAY=localhost:10.0"
echo "  # or"
echo "  export DISPLAY=:10.0"
echo ""
echo "Then test:"
echo "  xeyes"
echo ""
echo "If xeyes works, then run:"
echo "  source /home/hpalin/py311/bin/activate"
echo "  python3 object_detection.py --viewer"
echo ""
